config/routes.rb
Rails.application.routes.draw do

  get 'profile_notes/index'

   devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

   resources :teams, :roles, :meetings, :meeting_notes, :todos, :todo_items, :profile_notes

   resources :users, except: :create do
    resources :profile_notes, only: [:new, :edit, :show, :index]
    collection do   
     post :create_user
    end
    member do
      get :all_meetings
    end
    
   end

   resources :meetings do
    resources :meeting_notes, only: [:new, :edit, :show, :index]
    resources :todos, only: [:new, :edit, :show, :index]
   end
   # get '/users/:id/all_meetings', to: 'meetings#all_meetings'

   get '/agenda' => 'meetings#agenda'

   get '/note' => 'meetings#note', as: :show_all_notes

   root 'meetings#index'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	
	belongs_to :creator, class_name: "User", foreign_key: :creator_id
	belongs_to :guest, class_name: "User", foreign_key: :guest_id
	has_many :meeting_notes, :dependent => :destroy
	has_many :todos, :dependent => :destroy

	accepts_nested_attributes_for :meeting_notes

	RECURRING_STATUS = ['Weekly','Bi-weekly', 'Monthly']

	validates_presence_of :name, :date, :guest_id

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
	before_action :get_meeting, only: [:update, :destroy, :show]
	respond_to :js

	def index
		@meeting = Meeting.new
		@meeting_note = @meeting.meeting_notes.new
		@meetings = current_user.created_meetings.order("id ASC") + current_user.invited_meetings.order("id ASC")
		@upcoming_meetings = current_user.created_meetings.where('date >= ?', Date.current).order("id ASC") + current_user.invited_meetings.where('date >= ?', Date.current).order("id ASC")
		@past_meetings = current_user.created_meetings.where('date < ?', Date.current).order("id ASC") + current_user.invited_meetings.where('date < ?', Date.current).order("id ASC")		
	end

	def new
		@meeting = Meeting.new
		@meeting_note = @meeting.meeting_notes.new
	end

	def create
		@guest_id = params["guest_id"]
		@date = params["date"]
		@name = params["name"]
		@content = params["content"]
		@agenda = params["agenda"]
		@meeting = Meeting.create!(agenda: @agenda, creator_id: current_user.id, guest_id: @guest_id, date: @date, name: @name)
		@meeting_notes = MeetingNote.create!(content: @content, creator_id: current_user.id, meeting_id: @meeting.id)
		if !@meeting.meeting_notes.first.content.nil?
			@meeting.meeting_notes.first.creator_id = current_user.id
		end
		@meeting.meeting_notes.first.creator_id = current_user.id
		if !@meeting.save
			flash[:alert] = @meeting.errors.full_messages
		end
		if @meeting.meeting_notes.first.content == ""
			MeetingNote.last.delete #remove last meeting note as the value is blank
		end
		notify_guest(@meeting)
		render json: { message: 'meeting created', date: @meeting.date, guest: User.find(@meeting.guest_id).name, topic: @meeting.name }, status: 200
	end

	def get_guest_list
		guest_list = User.where.not(:id => current_user.id)
	end

	def check_meeting_status(meeting)
		@meeting = meeting
		if @meeting.status == 'accepted'
			set_status_to_scheduled(@meeting)
			google_calendar_create_host(@meeting)
			google_calendar_create_guest(@meeting)
		end
	end

	def google_calendar_create_host(meeting)
		@meeting = meeting 
		event = {
                'summary' => @meeting.name,
                'location' => 'Piktochart HQ at Suntech',
                'start' => {
                'dateTime' => @meeting.date.to_datetime},  
               	'end' => {         
		          'dateTime' => @meeting.date.to_datetime},                 
		          'attendees' => User.find(@meeting.guest_id).name          
                 }       
		token = User.find(@meeting.creator_id).access_token
      	client = Google::APIClient.new         
      	client.authorization.access_token = token
        service = client.discovered_api('calendar', 'v3')
        result = client.execute(:api_method => service.events.insert, :parameters => {'calendarId' => 'primary'},:body => JSON.dump(event),:headers => {'Content-Type' => 'application/json'})
	end

	def google_calendar_create_guest(meeting)
		@meeting = meeting 
		event = {
                'summary' => @meeting.name,
                'location' => 'Piktochart HQ at Suntech',
                'start' => {
                'dateTime' => @meeting.date.to_datetime},  
               	'end' => {         
		          'dateTime' => @meeting.date.to_datetime},                 
		          'attendees' => User.find(@meeting.guest_id).name          
                 }       
		token = current_user.access_token
      	client = Google::APIClient.new         
      	client.authorization.access_token = token
        service = client.discovered_api('calendar', 'v3')
        result = client.execute(:api_method => service.events.insert, :parameters => {'calendarId' => 'primary'},:body => JSON.dump(event),:headers => {'Content-Type' => 'application/json'})
	end

	def set_status_to_scheduled(meeting)
		@meeting = meeting
		@meeting.update(:status => 'scheduled')
	end

	def notify_guest(meeting)
		@meeting = meeting
		MeetingInvitationMailer.invite_user(@meeting,User.find(@meeting.guest_id),User.find(@meeting.creator_id)).deliver_now
	end

	def show 	
		render json: { message: 'meeting info', date: @meeting.date, guest: User.find(@meeting.guest_id).name, topic: @meeting.name, agenda: @meeting.agenda }, status: 200
		check_meeting_status(@meeting)
	end

	def edit
		@meeting = Meeting.find(params[:id])

	end

	def update
  		if @meeting.update(meeting_params)
  			check_meeting_status(@meeting)
    		render json: {message: "scheduled"}, status: 200
  		else
    		render 'edit'
  		end
	end

	def destroy
		@meeting.destroy
		redirect_to @meeting
	end

	private
	def get_meeting
		@meeting = Meeting.find(params[:id])
	end
	def meeting_params
		params.require(:meeting).permit(:status, :name, :date, :agenda, :recurring_status, :creator_id, :guest_id, meeting_notes_attributes: [:id, :creator_id, :meeting_id, :content])
	end

	

end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_edit_meeting_note_modal.html.erb
<div class="modal fade slide-up disable-scroll" id="editMeetingNote" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog ">
    <div class="modal-content-wrapper">
      <div class="modal-content" id="profileNotePopupContent">
        <div class="modal-header clearfix text-left">
          <p><span class="bold"><i class="fa fa-sticky-note-o" aria-hidden="true"></i>   Private Note</span>  <span class="pull-right"><i class="fa fa-lock" aria-hidden="true"></i> (Only you can see this private note)</span></p>
          <div class="progress">
            <div class="progress-bar-indeterminate progress-bar-complete"></div>
          </div>
        </div>
        <div class="modal-body">
          <form role="form" id="createMeetingForm">
            <div class="form-group-attached">
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group form-group-default">
                    <textarea type="text" name="meeting-note" class="form-control" id="edit-meeting-note"></textarea>
                    <%= hidden_field_tag :creator_id, @current_user.id %>                        
                  </div>
                </div>
              </div>
            </div>
          </form>
          <div class="row">
            <div class="col-md-12 profileNoteActionButtons">
              <button type="button" data-dismiss="modal" aria-hidden="true" class="pull-right btn btn-complete btn-rounded ">Cancel</button>
              <button type="button" id="updateMeetingNote" class="pull-right btn btn-complete btn-rounded ">Update</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meetings/_important_announcement.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">Important announcement</div>
      <div class="panel-controls">
        <ul>
          <li>
            <a data-toggle="close" class="portlet-close" href="#">
              <i class="portlet-icon portlet-icon-close"></i>
            </a>
          </li>
        </ul>
      </div>
  </div>
    <div class="panel-body">
      <div class="scrollable">
        <div class="demo-portlet-scrollable">
          <h3><span class="semi-bold">Important</span> announcement</h3>
          <p>Some important announcements go here!</p>
        </div>
      </div>
    </div>
</div>

app/views/meetings/_meeting_confirmation_modal.html.erb
<div class="modal fade slide-up disable-scroll" id="meetingConfirmation" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog ">
    <div class="modal-content-wrapper">
      <div class="modal-content">
        <div class="modal-header clearfix text-left">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
          </button>
          <h5><span class="bold">Invitation sent!</span></h5>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-12" id="confirmation-details">
              <p id="confirmation-name"></p>
              <p id="confirmation-date"></p>
              <p id="confirmation-topic"></p>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-4 m-t-10 sm-m-t-10">
              <button type="button" data-dismiss="modal" aria-hidden="true" id="dismissConfirmation" class="pull-left btn btn-complete btn-rounded m-t-5">Dismiss</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meetings/_meeting_invitation_modal.html.erb
<div class="modal fade stick-up" id="meetingInvitation" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header clearfix text-left">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
        </button>
        <h5 class="bold">Meeting Information</h5>
        <p></p>
      </div>
      <div class="modal-body">
        <p id="meeting-topic"></p>
        <p id="meeting-guest"></p>
        <p id="meeting-date"></p>
        <p id="meeting-agenda"></p>
        <div class="row">
          <div class="col-sm-6">
            <p class="small">By clicking yes, this meeting will be scheduled in your Google Calendar.</p>
          </div>
          <div class="col-sm-3 pull-right">
            <button id="cancelMeetingBtn" type="button" class="btn btn-danger btn-block m-t-5">No</button>
          </div>
          <div class="col-sm-3 pull-right">
            <button id="confirmMeetingBtn" type="button" class="btn btn-success btn-block m-t-5">Yes</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meetings/_new_meeting_modal.html.erb
<div class="modal fade slide-up disable-scroll" id="modalSlideUp" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog ">
    <div class="modal-content-wrapper">
      <div class="modal-content">
        <div class="modal-header clearfix text-left">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
          </button>
          <h5><span class="bold">Create new 1:1</span></h5>
          <div class="progress">
            <div class="progress-bar-indeterminate progress-bar-complete"></div>
          </div>
        </div>
        <div class="modal-body">
          <form role="form" id="createMeetingForm">
            <div class="form-group-attached">
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group form-group-default">
                    <label>With </label>
                    <%= collection_select :User, :guest_id, User.where.not(:id => current_user.id), :id, :name %>                       
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group form-group-default input-group date" id='datetimepicker1'>
                    <label>Date</label>  
                    <input type='text' id="date-data" class="form-control" name="meeting[date]" />
                    <span class="input-group-addon" id="dateTimePickerBtn">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>           
                  </div>
                </div>

                <div class="checkbox check-success">
                      <input type="checkbox" checked="checked" value="monthly" id="checkbox2">
                      <label for="checkbox2">I want to have 1:1 monthly at this date  </label>
                    </div>   
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group form-group-default">
                    <label>Topic</label>  
                    <input type="text" class="form-control" id="topic-data">                   
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group form-group-default">
                    <label>Agenda</label>  
                    <input type="text" class="form-control" id="agenda-data">                   
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group form-group-default">
                    <label>Private note</label>  
                    <input type="text" class="form-control" id="private-note-data">                   
                  </div>
                </div>
              </div>
            </div>
          </form>
          <div class="row">
            <div class="col-sm-4 m-t-10 sm-m-t-10">
              <button type="button" id="createMeeting" class="pull-left btn btn-complete btn-rounded m-t-5">Send an invite now!</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meetings/_new_meeting_note_modal.html.erb
<div class="modal fade slide-up disable-scroll" id="newMeetingNote" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog ">
    <div class="modal-content-wrapper">
      <div class="modal-content" id="profileNotePopupContent">
        <div class="modal-header clearfix text-left">
          <!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
          </button> -->
          <p><span class="bold"><i class="fa fa-sticky-note-o" aria-hidden="true"></i>   Private Note</span>  <span class="pull-right"><i class="fa fa-lock" aria-hidden="true"></i> (Only you can see this private note)</span></p>
          <div class="progress">
            <div class="progress-bar-indeterminate progress-bar-complete"></div>
          </div>
        </div>
        <div class="modal-body">
          <form role="form" id="createMeetingForm">
            <div class="form-group-attached">
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group form-group-default">
                    <textarea type="text" name="meeting-note" class="form-control" id="meeting-note-data"></textarea>
                    <%#= hidden_field_tag :creator_id, @user.id %>                        
                  </div>
                </div>
              </div>
            </div>
          </form>
          <div class="row">
            <div class="col-md-12 profileNoteActionButtons">
              <button type="button" data-dismiss="modal" aria-hidden="true" class="pull-right btn btn-complete btn-rounded ">Cancel</button>
              <button type="button" id="createMeetingNote" class="pull-right btn btn-complete btn-rounded ">Add</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meetings/_new_todo_modal.html.erb
<div class="modal fade slide-up disable-scroll" id="newTodo" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog ">
    <div class="modal-content-wrapper">
      <div class="modal-content" id="profileNotePopupContent">
        <div class="modal-header clearfix text-left">
          <!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
          </button> -->
          <p><span class="bold"><i class="fa fa-sticky-note-o" aria-hidden="true"></i>   Create New Todo List </p>
          <div class="progress">
            <div class="progress-bar-indeterminate progress-bar-complete"></div>
          </div>
        </div>
        <div class="modal-body">
          <form role="form" id="createMeetingForm">
            <div class="form-group-attached">
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group form-group-default">
                    <input type="text" placeholder="Put some title here" name="todo-name" class="form-control" id="new-todo-name">
                    <%= hidden_field_tag :creator_id, @current_user.id %>                        
                  </div>
                </div>
              </div>
            </div>
          </form>
          <div class="row">
            <div class="col-md-12 profileNoteActionButtons">
              <button type="button" data-dismiss="modal" aria-hidden="true" class="pull-right btn btn-complete btn-rounded ">Cancel</button>
              <button type="button" id="createTodo" class="pull-right btn btn-complete btn-rounded ">Add</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meetings/_todo_list.html.erb
<div class="panel panel-transparent">
  <div class="panel-heading">
    <div class="panel-title">To Do List</div>
  </div>
  <div class="panel-body">
    <div>
      <% TodoItem.first(5).each do |todo_item| %>
      <p class="small todo-item-date"><%= todo_item.created_at.strftime("%A, %d.%m.%Y") %></p>
      <p class="todo-item"> 
        <%= todo_item.item %>
      </p>
      <div class="clearfix"></div>
      <% end %>
    </div>
  </div>
</div>

app/views/meetings/agenda.html.erb
<h1>Agenda</h1>

<p>
  <strong>Meeting agenda:</strong>
  <%= @meeting.agenda %>
</p>

app/views/meetings/edit.html.erb
<h1>Edit Meeting</h1>

<%= form_for(@meeting) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <div class="container">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>

                    <input type='text' class="form-control" name="meeting[date]" placeholder="Enter Date" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(document).on('ready', function () {
              $('#datetimepicker1').datetimepicker({
                format: 'YYYY-MM-DD HH:mm'
              });
            });
        </script>
    </div>
</div>

  <p>
    <%= f.label :agenda %><br>
    <%= f.text_field :agenda %>
  </p>

  <p>
    <%= f.label :recurring_status %><br>
    <%= f.select :recurring_status, [['Weekly','Weekly'],['Bi-weekly','Bi-weekly'],['Monthly','Monthly']] %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/meetings/index.html.erb
<div class="meetings-list">
  <div class="row-fluid">
    <div class="col-md-12">
      <h2>
        <% if @upcoming_meetings.size >=1 %>
          Upcoming
        <% end %>
        <a class="btn pull-right btn-primary m-b-10" id="btnToggleSlideUpSize" data-remote="true" href="/meetings/new"><i class="fa fa-plus" aria-hidden="true"></i>   Create New 1:1</a>
      </h2>
    </div>
    
      <div class="col-md-8">
      <% @upcoming_meetings.each do |upcoming_meeting| %>
        <div class="card share full-width">
          <%= link_to meeting_path(upcoming_meeting.id) do %>
          <div class="card-header clearfix">
            <div class="pull-right">
              <p><%= upcoming_meeting.date.to_formatted_s(:short)   %> </p>
            </div>
            <div class="user-pic">
              <% if upcoming_meeting.creator_id == current_user.id %>
                <%= image_tag User.find(upcoming_meeting.guest_id).avatar.url(:thumb) %>
              <% else %>
                <%= image_tag User.find(upcoming_meeting.creator_id).avatar.url(:thumb) %>
              <% end %>
            </div>
            <h5>
              <% if upcoming_meeting.creator_id == current_user.id %>
                <%= User.find(upcoming_meeting.guest_id).name.split.map(&:capitalize)*' ' %>
              <% else %>
                <%= User.find(upcoming_meeting.creator_id).name.split.map(&:capitalize)*' ' %>
              <% end %>
            </h5>
            <div class="row">
              <h6>Meeting is scheduled at  
                <span class="location semi-bold"><i class="fa fa-calendar" aria-hidden="true"></i></i> 
                <%= upcoming_meeting.date.to_formatted_s(:short)   %></span>
                <span class="pull-right bold" style="position: relative; left: 8%;"><%= upcoming_meeting.name %></span>
              </h6>
            </div>
          </div>
      <% end %>
          <div class="discussion">
              <p><i class="fa fa-commenting-o" aria-hidden="true"></i>   What do you want to discuss</p>
          </div>
          <div class="card-description">
            <p><%= upcoming_meeting.agenda %></p>
            <!-- <div class="via">via themeforest</div> -->
            <% if upcoming_meeting.meeting_notes.size == 0 %>
              <div class="actionButton">
                <i role="button" data-meetingID="#{upcomming_meeting.id}" class="fa fa-pencil newMeetingNoteSlideUp" aria-hidden="true"></i>
                <p><%= hidden_field_tag 'upcoming_meeting_id', upcoming_meeting.id %></p>
              </div>
            <% end %>
          </div>
          <% if upcoming_meeting.meeting_notes.size > 0 %>
            <% upcoming_meeting.meeting_notes.each do |meeting_note| %>
              <div class="card-description meeting-notes">
                <p class="bold"><i class="fa fa-sticky-note-o" aria-hidden="true"></i>    Private Note</p>
                <br>
                <p><i class="fa fa-clock-o" aria-hidden="true"></i>     Created on <%= meeting_note.created_at.strftime("%A, %d.%m.%Y") %>     <span class="small"><i class="fa fa-lock" aria-hidden="true"></i>     (Only you can see)</span></p>
                <p><%= hidden_field_tag 'meeting_note_id', meeting_note.id %></p> 
                <p><%= hidden_field_tag 'meeting_id', meeting_note.meeting_id %></p> 
                <p id="meetingNoteContent"><%= meeting_note.content %></p>
                <!-- <div class="via">via themeforest</div> -->
                <div class="actionButton">
                  <i role="button" class="fa fa-pencil editMeetingNoteSlideUp" aria-hidden="true"></i>
                  <a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/meeting_notes/<%= meeting_note.id %>"><i role="button" class="fa fa-trash-o" aria-hidden="true"></i></a>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <% if @past_meetings.size >=1 %>
        <h2>Past</h2>
      <% end %>
      <% @past_meetings.each do |past_meeting| %>
        <div class="card share full-width">
          <!-- <div class="circle" data-toggle="tooltip" title="Label" data-container="body"></div> -->
          <%= link_to meeting_path(past_meeting.id) do %>
          <div class="card-header clearfix">
            <div class="pull-right">
              <%= past_meeting.name %> <i class="fa fa-comment-o"></i>
            </div>
            <div class="user-pic">
              <% if past_meeting.creator_id == current_user.id %>
                <%= image_tag User.find(past_meeting.creator_id).avatar.url(:thumb) %>
              <% else %>
                <%= image_tag User.find(past_meeting.guest_id).avatar.url(:thumb) %>
              <% end %>
            </div>
            <h5>
              <% if past_meeting.creator_id == current_user.id %>
                <%= User.find(past_meeting.creator_id).name.split.map(&:capitalize)*' ' %>
              <% else %>
                <%= User.find(past_meeting.guest_id).name.split.map(&:capitalize)*' ' %>
              <% end %>
            </h5>
            <h6>Meeting is scheduled at  
              <span class="location semi-bold"><i class="fa fa-calendar" aria-hidden="true"></i></i> 
              <%= past_meeting.date.to_formatted_s(:short)   %></span>
              <span class="pull-right bold" style="position: relative; left: 8%;"><%= past_meeting.name %></span>
            </h6>
          </div>
          <% end %>

          <div class="card-description">
            <p><%= past_meeting.agenda %></p>
            <% if past_meeting.todos.size  == 0 %>
              <div class="actionButton">
                <i role="button" class="fa fa-list-ul newTodoSlideUp" aria-hidden="true"></i>
                <p><%= hidden_field_tag 'past_meeting_id', past_meeting.id %></p>
              </div>
            <% end %>
          </div>
          <% if past_meeting.meeting_notes.size > 0 %>
            <% past_meeting.meeting_notes.each do |meeting_note| %>
              <div class="card-description meeting-notes" >
                <p class="bold"><i class="fa fa-sticky-note-o" aria-hidden="true"></i>    Private Note</p>
                <br>
                <p><i class="fa fa-clock-o" aria-hidden="true"></i>     Created on <%= meeting_note.created_at.strftime("%A, %d.%m.%Y") %>     <span class="small"><i class="fa fa-lock" aria-hidden="true"></i>     (Only you can see)</span></p> 
                <p><%= meeting_note.content %></p>

                
              </div>
            <% end %>
          <% end %>
          <% if past_meeting.todos.size > 0 %>
            <% past_meeting.todos.each do |todo| %>
              <div class="card-description todo-div" style="border-top: 1px solid grey;">
                <p><i class="fa fa-list-ul" aria-hidden="true"></i> To do list for me </p>
                <div class="todoList">
                <% todo.todo_items.each do |todo_item| %>
                  <div class="checkbox check-success" id="todoItemChecker">
                    <input type="checkbox" id="<%= todo_item.id%>" <% if todo_item.is_completed == true %><%= checked="checked" %> <% end %> >
                    
                    <label for="<%= todo_item.id%>"><%= todo_item.item %></label>
                    <span class="pull-right">
                      <i role="button" class="fa fa-pencil" aria-hidden="true"></i>&nbsp;&nbsp;             
                      <a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/todo_items/<%= todo_item.id %>"><i role="button" class="fa fa-trash-o" aria-hidden="true"></i></a>
                    </span>
                    
                  </div>
                
                <% end %>
                </div>
                  <div class="row">
                    <div class="col-md-12">
                      <input type="hidden" id="getTodoID" value="<%= todo.id %>"> 
                      <input type="text" class="addTodo" width=inherit placeholder="Add an item" name="addTodo">
                    </div>
                  </div>
              </div>
            <% end %>
          <% end %>

          <div class="card-content">
            <ul class="buttons ">
              <li><a href="#"><i class="fa fa-expand"></i></a></li>
              <li><a href="#"><i class="fa fa-heart-o"></i></a></li>
            </ul>
            <!-- <img alt="Social post" src="../assets/img/social-post-image.png"> -->
          </div>
        </div>
      <% end %>

      </div>

    <div class="col-md-4">
      <!-- important announcement section -->
      <%= render 'important_announcement' %>
      <!-- todo list section -->
      <%= render 'todo_list' %>
    </div>
  </div>
</div>
<!-- meeting confirmation modal -->
<%= render 'meeting_confirmation_modal' %>
<!-- new meeting modal -->
<%= render 'new_meeting_modal' %>
<!-- edit meeting note modal -->
<%= render 'new_meeting_note_modal' %>
<!-- edit meeting note modal -->
<%= render 'edit_meeting_note_modal' %>
<!-- new todo modal -->
<%= render 'new_todo_modal' %>
<!-- meeting invitation modal -->
<%= render 'meeting_invitation_modal' %>

app/views/meetings/note.html.erb
<h1>Note</h1>

<p>
  <strong>Meeting private note:</strong>
  <% @notes.each do |note| %>
  	<%= note.content %>
  	<%= link_to 'Edit Note', edit_meeting_note_path(note.id) %></td>
  <% end %>
</p>

app/views/meetings/todo.html.erb
<h1>Meeting Todo</h1>