config/routes.rb
Rails.application.routes.draw do

  get 'profile_notes/index'

   devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

   resources :teams, :roles, :meetings, :meeting_notes, :todos, :todo_items, :profile_notes

   resources :users, except: :create do
    resources :profile_notes, only: [:new, :edit, :show, :index]
    collection do   
     post :create_user
    end
    member do
      get :all_meetings
    end
    
   end

   resources :meetings do
    resources :meeting_notes, only: [:new, :edit, :show, :index]
    resources :todos, only: [:new, :edit, :show, :index]
   end
   # get '/users/:id/all_meetings', to: 'meetings#all_meetings'

   get '/agenda' => 'meetings#agenda'

   get '/note' => 'meetings#note', as: :show_all_notes

   root 'meetings#index'

end

app/models/meeting_note.rb
class MeetingNote < ActiveRecord::Base
	belongs_to :meeting 
	belongs_to :creator, class_name: "User", foreign_key: :creator_id

end

app/controllers/meeting_notes_controller.rb
class MeetingNotesController < ApplicationController
	def index
		@meetingnotes = MeetingNote.where(:meeting_id => params[:meeting_id], :creator_id => current_user.id)
	end

	def new
		@meeting_id = params[:meeting_id]
		@creator_id = current_user.id
		@meetingnote = MeetingNote.new
	end

	def create
		@meetingnote = MeetingNote.new(meetingnote_params)
		@meetingnote.save
		redirect_to (meeting_path(:id => @meetingnote.meeting_id))
	end

	def show 
		@meetingnote = MeetingNote.find(params[:meeting_id]).where(:creator_id => current_user.id)
		puts @meetingnote
	end

	def edit
		@meetingnote = MeetingNote.find(params[:id])
	end

	def update
		@meetingnote = MeetingNote.find(params[:id])
 
  		if @meetingnote.update(meetingnote_params)
    		render json: { message: 'updated' }, status: 200
  		else
    		render 'edit'
  		end
	end

	def destroy
		@meetingnote = MeetingNote.find(params[:id])
		@meetingnote.destroy
		redirect_to (:back)
	end

	private
	def meetingnote_params
		params.require(:meeting_note).permit(:content, :meeting_id, :creator_id )
	end
end

app/helpers/meetingnotes_helper.rb
module MeetingnotesHelper
end

app/views/meeting_notes/edit.html.erb
<h1>Edit Meeting note</h1>

<%= form_for(@meetingnote) do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/meeting_notes/index.html.erb
<h1>My private meeting notes</h1>
<%= link_to 'Create new meeting note', new_meeting_meeting_note_path %>

<table>
  <tr>
    <th>Meeting ID</th>
    <th>Meeting Note ID</th>
    <th>Content</th>
    <th>Creator</th>
  </tr>
 
  <% @meetingnotes.each do |meetingnote| %>
    <tr>
      <td><%= meetingnote.meeting_id %></td>
      <td><%= meetingnote.id %></td>
      <td><%= meetingnote.content %></td>
      <td><%= User.find(meetingnote.creator_id).name %></td>
      <td><%= link_to 'Edit meeting note ', edit_meeting_meeting_note_path(:id => meetingnote.id) %></td>
      <td><%= link_to 'Delete meeting note', meeting_note_path(meetingnote), method: :delete, data: {confirm: "Are you sure?"} %></td>
  
    </tr>
  <% end %>
</table>

app/views/meeting_notes/new.html.erb
<h1>New Meeting note</h1>

<%= form_for(@meetingnote) do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
    <%= f.hidden_field :meeting_id, :value => params[:meeting_id] %>
    <%= f.hidden_field :creator_id, :value => current_user.id %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>