config/routes.rb
Rails.application.routes.draw do

  get 'profile_notes/index'

   devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

   resources :teams, :roles, :meetings, :meeting_notes, :todos, :todo_items, :profile_notes

   resources :users, except: :create do
    resources :profile_notes, only: [:new, :edit, :show, :index]
    collection do   
     post :create_user
    end
    member do
      get :all_meetings
    end
    
   end

   resources :meetings do
    resources :meeting_notes, only: [:new, :edit, :show, :index]
    resources :todos, only: [:new, :edit, :show, :index]
   end
   # get '/users/:id/all_meetings', to: 'meetings#all_meetings'

   get '/agenda' => 'meetings#agenda'

   get '/note' => 'meetings#note', as: :show_all_notes

   root 'meetings#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  #after_create :init_user_to_peer

  belongs_to :team
  has_many :profile_notes
  has_one :user_role
  has_one :role, through: :user_role 

  has_many :created_meetings, class_name: "Meeting", foreign_key: :creator_id
  has_many :invited_meetings, class_name: "Meeting", foreign_key: :guest_id

  has_many :meeting_notes
  has_many :todos
  has_many :todo_items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
     :omniauthable, :omniauth_providers => [:google_oauth2]

  #paperclip
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/img/profiles/avatar.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  accepts_nested_attributes_for :user_role

  #validates_presence_of :name, :email, :password

  def self.find_for_google_oauth2(auth)
      data = auth.info
      user = User.where(:provider => auth.provider, :uid => auth.uid ).first

      if user
        user.access_token = auth.credentials.token
        user.refresh_token = auth.credentials.refresh_token
        user.save
        return user
      else
        registered_user = User.where(:email => auth.info.email).first
        if registered_user
          registered_user.access_token = auth.credentials.token
          registered_user.refresh_token = auth.credentials.refresh_token
          registered_user.save
          return registered_user
        else
          user = User.create(name: data["name"],
            provider:auth.provider,
            email: data["email"],
            uid: auth.uid ,
            password: Devise.friendly_token[0,20],
            access_token: auth.credentials.token,
            refresh_token: auth.credentials.refresh_token
          )
        end
     end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.google_data"] && session["devise.google_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def google
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end 

  def admin?     
    if self.user_role.role_id == 4
      return true
    end
  end 

  def unity?     
    if self.user_role.role_id == 3
      return true
    end
  end 

  def team_leader?     
    if self.user_role.role_id == 2
      return true
    end
  end 

  def peer?     
    if self.user_role.role_id == 1
      return true
    end
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index 
		if current_user.team_leader?
			@users = User.all.where(:team_id => current_user.team_id)
		end
		if current_user.admin? || current_user.unity? 
			@users = User.all
		end
		if current_user.peer?
			@users= User.where(:id => current_user.id)
		end
	end

	def new
		if current_user.admin? || current_user.unity?
			@user = User.new
		end
	end

	def create_user
		if current_user.admin? || current_user.unity?
			@user = User.new(user_params)
			@user.email = @user.name + "@piktochart.com"
			@user.save
			redirect_to @user
		end
	end

	def edit
		@user = User.find(params[:id])
	end 

	def show
		@user = User.find(params[:id])
		@profile_notes = ProfileNote.where(receiver_id: @user.id, writer_id: current_user.id)
	end

	def update
		name = params["name"]
		email = params["email"]
		password = params["password"]
		avatar = params["avatar"]

		if !current_user.peer?
			@user = User.find(params[:id])
		else
			@user = current_user
		end
    	if @user.update_attributes(user_params)
    		if !params[:user_role_id].nil?
	    		user_role = @user.user_role
	    		user_role.role_id = params[:user_role_id]
	    		user_role.save
	    	end
      		flash[:notice] = "Update successfully"
      		redirect_to users_path
    	else
      		render 'edit'
      		flash[:notice] = "Update failed"
    	end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to @user
	end

	def all_meetings
		@user = User.find(params[:id])
		@meetings = @user.created_meetings.order("id ASC") + @user.invited_meetings.order("id ASC")
		@upcoming_meetings = @user.created_meetings.where('date >= ?', Date.current).order("id ASC") + @user.invited_meetings.where('date >= ?', Date.current).order("id ASC")
		@past_meetings = @user.created_meetings.where('date < ?', Date.current).order("id ASC") + @user.invited_meetings.where('date < ?', Date.current).order("id ASC")	
	end 

	private
	def user_params
		params.require(:user).permit(:avatar, :email, :password, :name, :status, :team_id, user_role_attributes: [:id, :role_id])
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_account_settings_modal.html.erb
<div class="modal fade slide-up disable-scroll" id="accountSettings" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog ">
    <div class="modal-content-wrapper">
      <div class="modal-content">
        <div class="modal-header clearfix text-left">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
          </button>
          <h5><span class="bold">Account Settings</span></h5>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-4" id="confirmation-details" style="text-align: center;">
            	<%= image_tag @user.avatar.url(:thumb), class: "img-circle" %>
            	<p><input type="file" id="avatar-data"></p>
            	<p style="line-height: 1%;"><a href="#">Remove Picture</a></p>
            </div>
            <div class="col-md-8">
            	<div class="row">
            		<div class="col-md-12">
            			<div class="form-group form-group-default">
		                    <label>Change Name</label>  
		                    <input type="text" class="form-control" id="name-data"> 
		                    <%= hidden_field_tag :user_id, current_user.id %>                   
		                </div>
            		</div>
            	</div>
            	<div class="row">
            		<div class="col-md-12">
            			<div class="form-group form-group-default">
		                    <label>Change Email</label>  
		                    <input disabled type="text" class="form-control" id="email-data" value="<%= @user.email %>">          
		                </div>
            		</div>
            	</div>         	
            	<div class="row">
            		<div class="col-md-12">
            			<div class="form-group form-group-default">
		                    <label>Change Password</label>  
		                    <input  disabled type="password" class="form-control" id="new-password-data">                   
		                </div>
            		</div>
            	</div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-4 m-t-10 sm-m-t-10">
              <button type="button" data-dismiss="modal" aria-hidden="true" id="saveAccountSettings" class="pull-left btn btn-complete btn-rounded m-t-5">Save Profile</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_new_profile_note_modal.html.erb
<div class="modal fade slide-up disable-scroll" id="newProfileNote" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog ">
    <div class="modal-content-wrapper">
      <div class="modal-content" id="profileNotePopupContent">
        <div class="modal-header clearfix text-left">
          <!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
          </button> -->
          <p><span class="bold"><i class="fa fa-sticky-note-o" aria-hidden="true"></i>   Private Note</span>  <span class="pull-right"><i class="fa fa-lock" aria-hidden="true"></i> (Only you can see this private note)</span></p>
          <div class="progress">
            <div class="progress-bar-indeterminate progress-bar-complete"></div>
          </div>
        </div>
        <div class="modal-body">
          <form role="form" id="createMeetingForm">
            <div class="form-group-attached">
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group form-group-default">
                    <textarea type="text" name="profile-note" class="form-control" id="profile-note-data"></textarea>
                    <%= hidden_field_tag :receiver_id, @user.id %>    	                  
                  </div>
                </div>
              </div>
            </div>
          </form>
          <div class="row">
            <div class="col-md-12 profileNoteActionButtons">
              <button type="button" data-dismiss="modal" aria-hidden="true" class="pull-right btn btn-complete btn-rounded ">Cancel</button>
              <button type="button" id="createProfileNote" class="pull-right btn btn-complete btn-rounded ">Add</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_team_members_modal.html.erb
<div class="modal fade slide-up disable-scroll" id="teamMembersInfo" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog ">
    <div class="modal-content-wrapper">
      <div class="modal-content">
        <div class="modal-header clearfix text-left">
          <h5><span class="bold">Team Members</span></h5>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-12">
              <div class="table-responsive">
                <div id="detailedTable_wrapper" class="dataTables_wrapper form-inline no-footer">
                  <table class="table table-hover table-detailed dataTable no-footer" id="detailedTable" role="grid">
                    <thead>
                      <tr role="row"><th class="sorting_disabled" rowspan="1" colspan="1">Name</th><th style="width: 136px;" class="sorting_disabled" rowspan="1" colspan="1">Position</th><th style="width: 136px;" class="sorting_disabled" rowspan="1" colspan="1">Status</th></tr>
                    </thead>
                    <tbody id="teamMember">
                      <% User.where(team_id: @user.team_id).each do |team_member| %>                        
                        <tr role="row" class="odd"  id="<%= team_member.id %>">
                          <td class="v-align-middle semi-bold"><i class="fa fa-user" aria-hidden="true"></i>  <%= team_member.name %></td>
                          <td class="v-align-middle">UI designer</td>
                          <td class="v-align-middle semi-bold">Active</td>
                        </tr>   
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <button type="button" style="margin-left: 10px;" data-dismiss="modal" aria-hidden="true" class="pull-left btn btn-complete btn-rounded">Dismiss</button>
          </div>
        </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/all_meetings.html.erb
<div class="meetings-list">
  <div class="row-fluid">
    <div class="col-md-12">
      <h2>
        <% if @upcoming_meetings.size >=1 %>
          Upcoming
        <% end %>
        <a class="btn pull-right btn-primary m-b-10" id="btnToggleSlideUpSize" data-remote="true" href="/meetings/new"><i class="fa fa-plus" aria-hidden="true"></i>   Create New 1:1</a>
      </h2>
    </div>
    
      <div class="col-md-8">
      <% @upcoming_meetings.each do |upcoming_meeting| %>
        <div class="card share full-width">
          <%= link_to meeting_path(upcoming_meeting.id) do %>
          <div class="card-header clearfix">
            <div class="pull-right">
              <p><%= upcoming_meeting.date.to_formatted_s(:short)   %> </p>
            </div>
            <div class="user-pic">
              <% if upcoming_meeting.creator_id == current_user.id %>
                <%= image_tag User.find(upcoming_meeting.guest_id).avatar.url(:thumb) %>
              <% else %>
                <%= image_tag User.find(upcoming_meeting.creator_id).avatar.url(:thumb) %>
              <% end %>
            </div>
            <h5>
              <% if upcoming_meeting.creator_id == current_user.id %>
                <%= User.find(upcoming_meeting.guest_id).name.split.map(&:capitalize)*' ' %>
              <% else %>
                <%= User.find(upcoming_meeting.creator_id).name.split.map(&:capitalize)*' ' %>
              <% end %>
            </h5>
            <div class="row">
              <h6>Meeting is scheduled at  
                <span class="location semi-bold"><i class="fa fa-calendar" aria-hidden="true"></i></i> 
                <%= upcoming_meeting.date.to_formatted_s(:short)   %></span>
                <span class="pull-right bold" style="position: relative; left: 8%;"><%= upcoming_meeting.name %></span>
              </h6>
            </div>
          </div>
      <% end %>
          <div class="discussion">
              <p><i class="fa fa-commenting-o" aria-hidden="true"></i>   What does <%= @user.name %> want to discuss</p>
          </div>
          <div class="card-description">
            <p><%= upcoming_meeting.agenda %></p>
          </div>
          <% if upcoming_meeting.meeting_notes.size > 0 %>
            <% upcoming_meeting.meeting_notes.each do |meeting_note| %>
              <div class="card-description meeting-notes">
                <p class="bold"><i class="fa fa-sticky-note-o" aria-hidden="true"></i>    Private Note</p>
                <br>
                <p><i class="fa fa-clock-o" aria-hidden="true"></i>     Created on <%= meeting_note.created_at.strftime("%A, %d.%m.%Y") %>     <span class="small"><i class="fa fa-lock" aria-hidden="true"></i>     (Only you can see)</span></p>
                <p id="meetingNoteContent"><%= meeting_note.content %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <% if @past_meetings.size >=1 %>
        <h2>Past</h2>
      <% end %>
      <% @past_meetings.each do |past_meeting| %>
        <div class="card share full-width">
          <!-- <div class="circle" data-toggle="tooltip" title="Label" data-container="body"></div> -->
          <%= link_to meeting_path(past_meeting.id) do %>
          <div class="card-header clearfix">
            <div class="pull-right">
              <%= past_meeting.name %> <i class="fa fa-comment-o"></i>
            </div>
            <div class="user-pic">
              <% if past_meeting.creator_id == current_user.id %>
                <%= image_tag User.find(past_meeting.creator_id).avatar.url(:thumb) %>
              <% else %>
                <%= image_tag User.find(past_meeting.guest_id).avatar.url(:thumb) %>
              <% end %>
            </div>
            <h5>
              <% if past_meeting.creator_id == current_user.id %>
                <%= User.find(past_meeting.creator_id).name.split.map(&:capitalize)*' ' %>
              <% else %>
                <%= User.find(past_meeting.guest_id).name.split.map(&:capitalize)*' ' %>
              <% end %>
            </h5>
            <h6>Meeting is scheduled at  
              <span class="location semi-bold"><i class="fa fa-calendar" aria-hidden="true"></i></i> 
              <%= past_meeting.date.to_formatted_s(:short)   %></span>
              <span class="pull-right bold" style="position: relative; left: 8%;"><%= past_meeting.name %></span>
            </h6>
          </div>
          <% end %>

          <div class="card-description">
            <p><%= past_meeting.agenda %></p>
          </div>
          <% if past_meeting.meeting_notes.size > 0 %>
            <% past_meeting.meeting_notes.each do |meeting_note| %>
              <div class="card-description meeting-notes" >
                <p class="bold"><i class="fa fa-sticky-note-o" aria-hidden="true"></i>    Private Note</p>
                <br>
                <p><i class="fa fa-clock-o" aria-hidden="true"></i>     Created on <%= meeting_note.created_at.strftime("%A, %d.%m.%Y") %>     <span class="small"><i class="fa fa-lock" aria-hidden="true"></i>     (Only you can see)</span></p> 
                <p><%= meeting_note.content %></p>    
              </div>
            <% end %>
          <% end %>
          <% if past_meeting.todos.size > 0 %>
            <% past_meeting.todos.each do |todo| %>
              <div class="card-description todo-div" style="border-top: 1px solid grey;">
                <p><i class="fa fa-list-ul" aria-hidden="true"></i> To do list for <%= @user.name %> </p>
                <div class="todoList">
                <% todo.todo_items.each do |todo_item| %>
                  <div class="checkbox check-success" id="todoItemChecker">
                    <input type="checkbox" disabled="disabled" id="<%= todo_item.id%>" <% if todo_item.is_completed == true %><%= checked="checked" %> <% end %> >                 
                    <label for="<%= todo_item.id%>"><%= todo_item.item %></label>                
                  </div>        
                <% end %>
                </div>
              </div>
            <% end %>
          <% end %>

          <div class="card-content">
            <ul class="buttons ">
              <li><a href="#"><i class="fa fa-expand"></i></a></li>
              <li><a href="#"><i class="fa fa-heart-o"></i></a></li>
            </ul>
            <!-- <img alt="Social post" src="../assets/img/social-post-image.png"> -->
          </div>
        </div>
      <% end %>

      </div>

    <div class="col-md-4">
      <!-- important announcement section -->
      <%= render 'meetings/important_announcement' %>
      <!-- todo list section -->
      <%= render 'meetings/todo_list' %>
    </div>
  </div>
</div>
<!-- meeting confirmation modal -->
<%= render 'meetings/meeting_confirmation_modal' %>
<!-- new meeting modal -->
<%= render 'meetings/new_meeting_modal' %>
<!-- meeting invitation modal -->
<%= render 'meetings/meeting_invitation_modal' %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for(@user) do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <% if current_user.team_leader? || current_user.admin? %>
    <p>
      <%= f.label :team %><br>
      <%= f.collection_select :team_id, Team.all, :id, :name %>
    </p>
  <% end %> 
  <% if current_user.admin? %>
    <p>
      <%= f.label :role %><br>
      <!--<%= f.collection_select :id, Role.all, :id, :name %>-->
      <%#= f.collection_radio_buttons :id, Role.all, :id, :name %>
      <% Role.all.each do |role| %>
        <%= radio_button_tag 'user_role_id', role.id, (@user.role.try(:id) == role.id) %> 
        <%= role.name %>
      <% end %>
    </p>
  <% end %>
  <%= image_tag @user.avatar.url(:medium) %>
  <%= f.file_field :avatar %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/index.html.erb
<h1>All user information</h1>

<%= link_to 'Create User', new_user_path %>

<table>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Team ID</th>
    <th>Role</th>
    <th>Info</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.name.split.map(&:capitalize)*' ' %></td>
      <td><%= user.team_id %></td>
      <td><%= user.role.try(:name) %></td>
      <td><%= link_to '  Edit User', edit_user_path(user.id) %></td>
      <td><%= link_to '  View Profile', user_path(user.id) %></td>
      <td><%#= link_to 'Leave a note for ' + user.name, :controller => "users", :action => "new_profile_note", :receiver_id => current_user.id, :writer_id => current_user.id %></td>
      <td><%= link_to '  Delete User', user, method: :delete, data: {confirm: "You sure?"} %></td>
    </tr>

  <% end %>
</table>

app/views/users/new.html.erb
<div class="add-member">
  <h3 class="semi-bold">Add New Member</h3>

  <%= form_for :user, url: { action: "create_user" } do |f| %>
    <div class="form-group">
      <label>Full Name</label>
      <%= f.text_field :name, class: "form-control", :required => true %>
    </div>
    
    <div class="form-group">
      <label>Team</label>
      <div class="input-group">
        <!-- <input type="text" class="form-control"> -->
        <%= f.collection_select :team_id, Team.all, :id, :name %>
        <span class="input-group-addon primary">
          <i class="fa fa-align-justify"></i> 
        </span>
      </div>                        
    </div>
                      
    <div class="form-group">
      <label>Role</label>
      <div class="input-group">
        <%= f.fields_for :user_role_attributes do |builder| %>
          <%= builder.collection_select :role_id, Role.all, :id, :name %>
        <% end %>
        <span class="input-group-addon primary">
          <i class="fa fa-align-justify"></i> 
        </span>
      </div>                        
    </div>
                      
    <div class="form-group">
      <label>Email</label>
      <div class="input-group">
        <%= f.text_field :email, class: "form-control",:required => true %>
        <span class="input-group-addon primary">
          @piktochart.com
        </span>
      </div>
    </div>
                      
    <div class="form-group">
      <label>Create a temporary password</label>
      <%= f.password_field :password, class: "form-control", :required => true %>
    </div>
                      
    <%= f.submit %>
                 
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-profile" style="text-align: center;">
	<h3 class="bold">Profile</h3>
	<div class="profile-pic img-circle">
		<%= image_tag @user.avatar.url(:thumb), class: "img-circle" %>
	</div>
	<h4 class="semi-bold"><%= @user.name.split.map(&:capitalize)*' ' %></h4>
  <% if @user.team_leader? %>
    <p>Head of <%= Team.find(current_user.team_id).name %></p>
    <p><a href="#" id="teamMembersInfoSlideUp">View all team members</a></p>
  <% end %>
	<% if @user.id != current_user.id  %>
		<%= link_to 'Add private note', new_user_profile_note_path(user_id: @user.id), remote: true,  class: "btn btn-rounded btn-info", id: "newProfileNoteSlideUp" %>
	<% end %>
	<p>Timezone : <%= Time.zone.name %></p>
	<p>Email: <%= @user.email %></p>
  <% if @user.id == current_user.id %>
    <p><a id="accountSettingsSlideUp" href="#">Account settings</a></p>
  <% end %>
  <% if @user.id == current_user.id && @user.admin? || @user.unity? %>
    <a href="/users/new" ><button class="btn btn-rounded btn-info">Add Member</button></a>
    <button class="btn btn-rounded btn-info">Delete Member</button>
  <% end %>
	<hr>
	<% if @profile_notes.size >0 %>
		<% @profile_notes.each do |profile_note| %>
			<div class="private-profile-notes">
				<span class="pull-right">
					<i role="button" class="fa fa-pencil" aria-hidden="true"></i>&nbsp;&nbsp;    					
					<a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/profile_notes/<%= profile_note.id %>"><i role="button" class="fa fa-trash-o" aria-hidden="true"></i></a>
				</span>				
				<p><i class="fa fa-sticky-note-o" aria-hidden="true"></i> Private note</p>
				<p><i class="fa fa-sticky-calendar-o" aria-hidden="true"></i> <%= profile_note.created_at %>  <span><i class="fa fa-lock" aria-hidden="true"></i> (Only you can see this private note)</span></p>
				<p id="profileNote"><%= profile_note.content %></p>
			</div>
		<% end %>
	<% end %>
</div>

<!-- new profile modal -->
<%= render 'new_profile_note_modal' %>
<!-- account settings modal -->
<%= render 'account_settings_modal' %>
<!-- all team members modal -->
<%= render 'team_members_modal' %>

app/views/users/welcome.html.erb
<h1>Welcome page</h1>

<%= form_for :user, url: users_path  do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>