config/routes.rb
Rails.application.routes.draw do

  get 'profile_notes/index'

   devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

   resources :teams, :roles, :meetings, :meeting_notes, :todos, :todo_items, :profile_notes

   resources :users, except: :create do
    resources :profile_notes, only: [:new, :edit, :show, :index]
    collection do   
     post :create_user
    end
    member do
      get :all_meetings
    end
    
   end

   resources :meetings do
    resources :meeting_notes, only: [:new, :edit, :show, :index]
    resources :todos, only: [:new, :edit, :show, :index]
   end
   # get '/users/:id/all_meetings', to: 'meetings#all_meetings'

   get '/agenda' => 'meetings#agenda'

   get '/note' => 'meetings#note', as: :show_all_notes

   root 'meetings#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
	belongs_to :meeting
	belongs_to :creator, class_name: "User", foreign_key: :creator_id
	has_many :todo_items, :dependent => :destroy

	accepts_nested_attributes_for :todo_items
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index 
		@todos = Todo.where(meeting_id: params[:meeting_id])		
	end

	def new
		@todo = Todo.new
		@todo_item = @todo.todo_items.new
	end 

	def create
		creator_id = current_user.id
		is_deleted = false
		is_completed = false 
		@todo = Todo.new(todo_params)
		@todo.creator_id = current_user.id
		@todo.is_completed = is_completed
		@todo.todo_items.each do |todo_item|
			todo_item.creator_id = current_user.id
			todo_item.is_completed = is_completed
			todo_item.is_deleted = is_deleted
		end
		@todo.save
		redirect_to (meeting_path(:id => @todo.meeting_id))
	end

	def show
		@todo = Todo.find(params[:id])
	end 

	def edit
		@todo = Todo.find(params[:id])
		@todo_items = @todo.todo_items	
	end 

	def update
		@todo = Todo.find(params[:id])
  		if @todo.update(todo_params)
    		redirect_to (meeting_path(:id => @todo.meeting_id))
  		else
    		render 'edit'
  		end
	end

	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		redirect_to (meeting_path(:id => @todo.meeting_id))
	end

	private
	def todo_params
		params.require(:todo).permit(:meeting_id, :name, :is_completed, :creator_id, todo_items_attributes: [:todo_id, :id, :item, :is_completed, :is_deleted, :creator_id])
	end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_new_item.erb
	
	<input placeholder="Insert item here" type="text" name="todo[todo_items_attributes][][item]" id="todo_todo_items_attributes_0_item">

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>

<%= form_for(@todo) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <!-- <div id="todolist">
  	<%#= f.fields_for :todo_items do |builder| %>
  		<%#= builder.text_field :item %>
  		<br><button id="addTodoBtn" type="button" class="btn btn-info">Add</button>

  		<ol class="item-list">

  		</ol>
  	
  	<%# end %>
  </div> -->
  <%= f.fields_for :todo_items do |builder| %>

  	<%= builder.text_field :item %>
  	<br>
  <% end %>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/todos/index.html.erb
<h1>All todos</h1>
<%= link_to 'Create new Todo', new_meeting_todo_path %>
<table>
  <tr>
    <th>Meeting ID</th>
    <th>Name</th>
    <th>ID</th>

  </tr>
 
  <% @todos.each do |todo| %>
    <tr>
      <td><%= todo.meeting_id %></td>
      <td><%= todo.name %></td>
      <td><%= todo.id %></td>
      <td><%= link_to 'View Todo', meeting_todo_path(:id => todo.id) %></td>
      <td><%= link_to 'Edit Todo', edit_meeting_todo_path(:id => todo.id) %></td>
      <td><%= link_to 'Delete Todo', todo, method: :delete, data: {confirm: "You sure?"} %></td>
      <% end %>

    </tr>


</table>

app/views/todos/new.html.erb
<h1>Create new todo</h1>

<%= form_for(@todo) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <%= f.hidden_field :meeting_id, :value => params[:meeting_id] %>
    <%= f.hidden_field :creator_id, :value => params[:user_id] %>
  </p>

  <div id="todolist">
  	<%= f.fields_for :todo_items do |builder| %>
  		<%= builder.label 'Add item' %>
  		<br><button id="addTodoBtn" type="button" class="btn btn-info">Add</button>

  		<ol class="item-list">

  		</ol>
  	
  	<% end %>
  </div>


  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/todos/show.html.erb
<h1>Todo </h1>
<%= link_to 'Edit Todo', edit_meeting_todo_path(:id => @todo.id, :meeting_id => @todo.meeting_id) %>
<%= link_to 'Delete Todo', @todo, method: :delete, data: {confirm: "You sure?"} %>

<p>
  <strong>Meeting ID:</strong>
  <%= @todo.meeting_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @todo.name %>
</p>

<p>
  <strong>Item:</strong>
  <% @todo.todo_items.collect do |i|  %>
    <%= i.item %>
    <%= check_box :TodoItem, i.item %>
    <br>
  <% end %>
</p>